version: '3'
services:
  material-mini-crm:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - '3000:3000'

  material-mini-node:
    build:
      context: ./node_backend/src/
      dockerfile: Dockerfile
    ports:
      - '3001:3001'
    volumes:
      - ./node_backend/src:/app
      - node_modules:/app/node_modules
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres
    ports:
      - '127.0.0.1:5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 3

volumes:
  postgres-data:
  node_modules:
